# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 20:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.CharField(max_length=20)),
                ('date', models.DateField()),
                ('country', models.CharField(max_length=100)),
            ],
        ),
    ]
