# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-04-15 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boroda', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='nameofprod',
            field=models.CharField(default=123, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.CharField(max_length=50),
        ),
    ]
